# Generated by Django 5.1.3 on 2024-12-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['start_mail'], 'permissions': [('set_active', 'Set active'), ('can_edit', 'Can Edit')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['fio'], 'permissions': [('can_edit', 'Can Edit')], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AlterModelOptions(
            name='try',
            options={'ordering': ['send_time'], 'permissions': [('can_edit', 'Can Edit')], 'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
    ]
